tools:
  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

languages:
  lua:
    - <<: *lua-lua-format

  sh:
    - <<: *sh-shellcheck

  vim:
    - <<: *vim-vint
